# Generated by Django 3.1.7 on 2021-03-21 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IT_help', '0001_initial'),
    ]

    operations = [
    ]
