# Generated by Django 3.1.7 on 2021-03-23 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IT_help', '0003_user_info'),
    ]

    operations = [
    ]
