# Generated by Django 3.1.7 on 2021-03-23 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IT_help', '0004_auto_20210323_2317'),
    ]

    operations = [
    ]
