# Generated by Django 3.1.7 on 2021-04-04 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IT_help', '0005_auto_20210323_2327'),
    ]

    operations = [
    ]
