# Generated by Django 3.1.7 on 2021-04-04 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IT_help', '0007_auto_20210404_1603'),
    ]

    operations = [
    ]
